version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: tox
    versions:
    - ">= 3.10.a, < 3.11"
  - dependency-name: tox
    versions:
    - ">= 3.11.a, < 3.12"
  - dependency-name: tox
    versions:
    - ">= 3.12.a, < 3.13"
  - dependency-name: tox
    versions:
    - ">= 3.13.a, < 3.14"
  - dependency-name: tox
    versions:
    - "> 3.7.0, < 4"
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: pylint
    versions:
    - 2.6.2
    - 2.7.1
    - 2.7.2
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pylint-django
    versions:
    - 2.4.2
  - dependency-name: sphinx-rtd-theme
    versions:
    - 0.5.1
  - dependency-name: twine
    versions:
    - 3.3.0
  - dependency-name: django-debug-toolbar
    versions:
    - "3.2"
  - dependency-name: cryptography
    versions:
    - "3.2"
  - dependency-name: pytest-django
    versions:
    - 4.1.0
