# -*- coding: utf-8 -*-
# pylint: disable=missing-docstring,invalid-name,redefined-builtin

# Configuration file for the Sphinx documentation builder.
#
# Sphinx documentation: http://www.sphinx-doc.org/en/master/config

# -- Required imports --------------------------------------------------------
import os
import sys
import django
from django.conf import settings


# -- Path setup --------------------------------------------------------------
# Path to any external modules (i.e. outside of the docs directory)
sys.path.insert(0, os.path.abspath('../')) # Parent directory


# -- Project information -----------------------------------------------------
from subscriptions import __version__ # pylint: disable=wrong-import-position

project = 'django-flexible-subscriptions'
copyright = '2018, Joshua Robert Torrance'
author = 'Joshua Robert Torrance'
version = __version__
release = __version__


# -- General configuration ---------------------------------------------------
# Sphinx extensions
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
]

# Template paths (relative to this directory)
templates_path = []

# Suffix(es) of source filenames
source_suffix = '.rst'

# Master toctree document.
master_doc = 'index'

# Language for content autogenerated by Sphinx.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files (also affects
# html_static_path and html_extra_path)
exclude_patterns = [
    '_build', 'Thumbs.db', '.DS_Store', 'subscriptions/migrations',
]

# The name of the Pygments (syntax highlighting) style to use
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------
# HTML theme to use
html_theme = 'sphinx_rtd_theme'

# Path to any custom static files (overrides defaults if names match)
html_static_path = []


# -- Options for HTMLHelp output ---------------------------------------------
# Output file base name for HTML help builder
htmlhelp_basename = 'django-flexible-subscriptions-doc'


# -- Options for LaTeX output ------------------------------------------------
latex_elements = {}

# Grouping the document tree into LaTeX files - list of tuples as follows:
# (source start file, target name, title, author,
# documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        'django-flexible-subscriptions.tex',
        'django-flexible-subscriptions Documentation',
        'Joshua Robert Torrance',
        'manual'
    ),
]


# -- Options for manual page output ------------------------------------------
# One entry per manual page - list of tuples as follows:
# (source start file, name, description, authors, manual section)
man_pages = [
    (
        master_doc,
        'django-flexible-subscriptions',
        'django-flexible-subscriptions Documentation',
        [author],
        1
    ),
]


# -- Options for Texinfo output ----------------------------------------------
# Grouping the document tree into Texinfo files - list of tuples as follows:
# (source start file, target name, title, author, dir menu entry, description,
# category)
texinfo_documents = [
    (
        master_doc,
        'django-flexible-subscriptions',
        'django-flexible-subscriptions Documentation',
        author,
        'A subscription and recurrent billing application for Django.',
        'Miscellaneous'
    ),
]


# -- Options and settings for autodoc ----------------------------------------
# Any autodoc imports to mock to prevent import errors
autodoc_mock_imports = []

# Minimal Django settings to import subscriptions module for autodoc
django_settings = {
    'DATABASES': {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    },
    'INSTALLED_APPS': {
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.sites',
        'subscriptions',
    },
    'MIDDLEWARE': [
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
    ],
    'ROOT_URLCONF': 'subscriptions.urls',
    'TEMPLATES': [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'APP_DIRS': True,
        },
    ],
}

settings.configure(**django_settings)

# Initiate Django
django.setup()


# -- Options for napoleon ----------------------------------------------------
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_private_with_doc = False
